pipeline {
    agent any

    stages {
        stage('Setup') {
            steps {
                git branch: 'main', url: 'https://github.com/rm-oliveira/TCC-EBAC.git'
                bat '''cd UI
                npm install'''
            }
        }
        stage('Test') {
            steps {
                bat '''cd UI
                set NO_COLOR=1
                npx cypress run'''
            }
        }
    }
}